/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./../src/components/global/BottomNav.vue')['default']
    Loading: typeof import('./../src/components/global/Loading.vue')['default']
    Login: typeof import('./../src/components/Login.vue')['default']
    NestedReply: typeof import('./../src/components/reply/NestedReply.vue')['default']
    NotificationsList: typeof import('./../src/components/notifications/NotificationsList.vue')['default']
    Post: typeof import('./../src/components/post/Post.vue')['default']
    PostActions: typeof import('./../src/components/post/PostActions.vue')['default']
    PostContent: typeof import('./../src/components/post/PostContent.vue')['default']
    PostEmbed: typeof import('./../src/components/post/PostEmbed.vue')['default']
    PostEmbedExternal: typeof import('./../src/components/post/PostEmbedExternal.vue')['default']
    PostEmbedRecord: typeof import('./../src/components/post/PostEmbedRecord.vue')['default']
    PostEmbedRecordWithMedia: typeof import('./../src/components/post/PostEmbedRecordWithMedia.vue')['default']
    PostHeader: typeof import('./../src/components/post/PostHeader.vue')['default']
    PostWrapper: typeof import('./../src/components/post/PostWrapper.vue')['default']
    RepostChip: typeof import('./../src/components/post/RepostChip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./../src/components/Timeline.vue')['default']
  }
}
